blog/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout_then_login
from blog import views

urlpatterns = [
    url(r'^$', views.MainPage.as_view(), name='main'),

    url(r'^posts/(?P<author>\w+)/(?P<pk>\d+)/$', views.DetailPost.as_view(), name='post'),
    url(r'^new_post/$', views.CreatePost.as_view(), name='create_post'),
    url(r'^delete_post/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete_post'),
    url(r'^delete_comment/(?P<pk>\d+)/$', views.DeleteComment.as_view(), name='delete_comment'),

    url(r'^profile/(?P<username>\w+)/$', views.Profile.as_view(), name='profile'),

    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', logout_then_login, name='logout')
]

blog_machineheads/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('blog.urls', namespace='blog'))
]

blog/models.py
# coding: utf-8

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.core import validators
from django.db import models


# Create your models here.
from django.utils import timezone
from django.utils.html import format_html


class MyUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField('Логин', max_length=30, unique=True,
                                help_text='Не более 30 символов.'
                                          ' Только латинские буквы, цифры и символ подчеркивания.',
                                validators=[
                                    validators.RegexValidator(r'\w+',
                                                              'Введите правильное имя пользователя. Оно '
                                                              'должно быть на английском языке и  '
                                                              'содержать только буквы, цифры и знак подчеркивания.',
                                                              'invalid'),
                                ],
                                error_messages={
                                    'unique': 'Пользователь с таким именем уже существует.',
                                })
    email = models.EmailField('Адрес электронной почты', unique=True,
                              error_messages={
                                  'unique': 'Пользователь с такой электронной почтой уже существует.',
                              })
    date_joined = models.DateField('Дата регистрации', default=timezone.now)
    first_name = models.CharField('Имя', max_length=20, blank=True, null=True)
    last_name = models.CharField('Фамилия', max_length=30, blank=True, null=True)
    is_staff = models.BooleanField('Статус персонала', default=False,
                                   help_text=u'Отметьте, если пользователь может входить'
                                             u' в административную часть сайта.')
    is_active = models.BooleanField(u'Активный', default=True,
                                    help_text=u'Отметьте, если пользователь должен считаться активным.'
                                              u' Уберите эту отметку вместо удаления учётной записи.')
    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return '{}'.format(self.username)

    class Meta:
        verbose_name = u'Пользователь'
        verbose_name_plural = u'Пользователи'

    def get_short_name(self):
        short_name = '{}'.format(self.username)
        return short_name

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name


class Post(models.Model):
    author = models.ForeignKey(MyUser, verbose_name='Автор')
    title = models.CharField('Заголовок', max_length=100)
    text = models.TextField('Текст публикации',
                            validators=[validators.RegexValidator(r'.*\S.*', 'Обязательное поле', 'invalid')])
    date_created = models.DateTimeField('Дата создания', auto_now_add=True)

    def __str__(self):
        return '{}'.format(self.title)

    def get_preview(self):
        if len(self.text) > 500:
            return format_html('{}...'.format(self.text[:500]))
        else:
            return format_html(self.text)

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'
        ordering = ('-date_created',)


class Comment(models.Model):
    author = models.ForeignKey(MyUser, verbose_name='Автор')
    post = models.ForeignKey(Post, verbose_name='Публикация')
    text = models.CharField('Текст комментария', max_length=1000,
                            validators=[validators.RegexValidator(r'.*\S.*', 'Обязательное поле', 'invalid')])
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}'.format(self.text)

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ('date_created',)

blog/forms.py
from django import forms
from blog import models


class PostForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'text']


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['text']

blog/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect

from django.urls import reverse
from django.views import generic
from django.views.generic.edit import FormMixin
from blog import models, forms


class MainPage(generic.ListView):
    model = models.Post
    template_name = 'main_page.html'


class Profile(generic.DetailView):
    model = models.MyUser
    template_name = 'profile.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'


class CreatePost(generic.CreateView):
    model = models.Post
    template_name = 'posts/create_post.html'
    form_class = forms.PostForm

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        messages.success(self.request, 'Публикация добавлена')
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('blog:main')


# FormMixin для выведения формы модели Comment одновременно с DetailView модели Post
class DetailPost(FormMixin, generic.DetailView):
    model = models.Post
    context_object_name = 'post'
    template_name = 'posts/detail_post.html'
    form_class = forms.CommentForm
    slug_field = 'author'
    slug_url_kwarg = 'author'
    object = None
    comment = None

    def get_context_data(self, **kwargs):
        context = super(DetailPost, self).get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.author = self.request.user
        comment.post = self.object
        comment.save()
        messages.success(self.request, 'Комментарий добавлен')
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('blog:post', args=(self.object.author, self.object.pk))


class DeletePost(generic.DeleteView):
    model = models.Post
    template_name = 'posts/delete_post.html'

    def get_success_url(self):
        return reverse('blog:profile', args=(self.object.author,))


class DeleteComment(generic.DeleteView):
    model = models.Comment
    template_name = 'posts/delete_comment.html'

    def get_success_url(self):
        return reverse('blog:post', args=(self.object.post.author, self.object.post.pk,))

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
{% if messages %}
    <ul>
    {% for message in messages %}
        <li>{{ message }}</li>
    {% endfor %}
    </ul>
{% endif %}
<a href={% url 'blog:main' %}>Главная</a>
{% if user.is_authenticated %}
    <a href={% url 'blog:create_post' %}>Новая публикация</a>
    <a href={% url 'blog:profile' request.user %}>Мой профиль</a>
    <a href={% url 'blog:logout' %}>Выход</a>
{% else %}
    <a href={% url 'blog:login' %}>Войти</a>
{% endif %}
<hr/>
{% block content %}{% endblock content %}
</body>
</html>

templates/change_form.html
{#шаблон для подключения редактора tinymce с помощью wysiwyg в админке#}

{% extends "admin/change_form.html" %}

{% load wysiwyg %}

{% block extrahead %}
	
	{{ block.super }}
	
	{% wysiwyg_setup %}
	
{% endblock %}

{% block extrastyle %}
	
	{{ block.super }}
	

	
{% endblock %}

{% block content %}
	
	{{ block.super }}
	
	{# Replace XXXXXXXX with field name: #}
	{% wysiwyg_editor "id_text" %}
	
	{% comment %}
		{# ckeditor custom config example #}
		{% wysiwyg_editor "id_XXXXXXXX" "id_XXXXXXXX_editor" "{ toolbar: 'compact_toolbar' }" %}
	{% endcomment %}
	
	{# ... add more here... #}

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block content %}
<h1>Логин</h1>
<form method="post" action="{% url 'blog:login' %}">
{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Войти">
</form>
{% endblock content %}

templates/main_page.html
{% extends 'base.html' %}
{% load pagination_tags %}
{% block title %}Главная{% endblock title %}
{% block content %}

    {% if post_list %}
        {% autopaginate post_list 5 %}
        <table>
        {% for post in post_list %}
            <tr>
                <td><h4><a href={% url 'blog:post' post.author post.id %}>{{ post.title }}</a></h4></td>
            </tr>
            <tr>
                <td><i><a href={% url 'blog:profile' post.author %}>{{ post.author }}</a> ({{ post.date_created }})</i></td>
            </tr>
            <tr>
                <td>{{ post.get_preview|safe }}<br/></td>
            </tr>
        {% endfor %}
        </table>
        <br/>
        {% paginate %}

    {% else %}
        <p>Публикаций нет.</p>
    {% endif %}
{% endblock content %}

templates/posts/create_post.html
{% load wysiwyg %}
{% wysiwyg_setup %}
<h2>Новая публикация</h2>
{% if user.is_authenticated %}
    <form method="post" action="{% url 'blog:create_post' %}">
        {% csrf_token %}
        <p><b>Заголовок: </b></p>{{ form.title }}
{#        при рендере текстового поля через {{form_text}} wysywyg не дает отправвляться post-запросу, использование textarea - вынужденный костыль #}
        <textarea id="id_text" name="text" placeholder="Введите текст"></textarea>
        <input type="submit" value="Добавить">
    </form>
{% else %}
    <p>Войдите, чтобы добавить новую публикацию.</p>
{% endif %}
{% wysiwyg_editor "id_text" %}

templates/posts/delete_comment.html
{% extends 'base.html' %}
{% block content %}
    {% if request.user == comment.author or request.user == comment.post.author %}
        <p>Вы уверены, что хотите удалить комментарий?</p>
        <form action="{% url 'blog:delete_comment' comment.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Да">
{#            <input type="button" value="Нет" onclick="location.href={% url 'blog:profile' request.user %}">#}
        </form>
        <a href={% url 'blog:post' comment.post.author.username comment.post.pk %}>
            <button>Нет</button>
        </a>
    {% else %}
        <p> Вы не являетесь автором комментария </p>
    {% endif %}
{% endblock content %}

templates/posts/delete_post.html
{% extends 'base.html' %}
{% block content %}
    {% if request.user == post.author %}
        <p>Вы уверены, что хотите удалить публикацию?</p>
        <form action="{% url 'blog:delete_post' post.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Да">
{#            <input type="button" value="Нет" onclick="location.href={% url 'blog:profile' request.user %}">#}
        </form>
        <a href={% url 'blog:profile' request.user.username %}>
            <button>Нет</button>
        </a>
    {% else %}
        <p> Вы не являетесь автором данной публикации </p>
    {% endif %}
{% endblock content %}

templates/posts/detail_post.html
{% extends 'base.html' %}
{% load wysiwyg %}
{% wysiwyg_setup %}

{% block title %}{{ post.title }}{% endblock title %}

{% block content %}
    <h2>{{ post.title }}</h2>
    {% if request.user == post.author %}<a href={% url 'blog:delete_post' post.id %}>Удалить</a>{% endif %}
    <p><i>Автор: {{ post.author }}</i></p>
    <p><i>Дата: {{ post.date_created }}</i></p>
    {{ post.text|safe }}
    <hr/>

    <p>Комментарии ({{ post.comment_set.all.count }})</p>
    <table>
        {% for comment in post.comment_set.all %}
            <tr>
                <td><i><a href={% url 'blog:profile' comment.author %}> {{ comment.author }}</a>
                    ({{ comment.date_created }})</i></td>
            </tr>
            <tr>
                <td><p>{{ comment.text }}</p></td>
                {% if request.user == post.author or request.user == comment.author %}
                    <td>
                        <a href={% url 'blog:delete_comment' comment.id %}>Удалить</a>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>

    {% if user.is_authenticated %}
        <form method="post" action="{% url 'blog:post' post.author post.id %}">
            {% csrf_token %}
            <textarea maxlength="1000" id="id_text" name="text" placeholder="Введите текст комментария"></textarea>
            <input type="submit" value="Отправить">
        </form>
    {% else %}
        <p>Войдите, чтобы оставить комментарий</p>
    {% endif %}
{% endblock content %}

templates/profile.html
{% extends 'base.html' %}
{% load pagination_tags %}
{% block title %}{{ myuser.username }}{% endblock title %}
{% block content %}
    <h2>{{ myuser.username }}</h2>
    <p>Зарегистрирован {{ myuser.date_joined }}</p>
    <p>{% if myuser.first_name %}{{ myuser.first_name }}{% endif %}
        {% if myuser.last_name %}{{ myuser.last_name }}{% endif %}
    </p>
    <hr/>

    {% if myuser.post_set.all %}
    <p><b>Публикации пользователя:</b></p>
    {% autopaginate myuser.post_set.all 5 %}
    <table>
        {% for post in myuser.post_set.all %}
            <tr>
                <td><h4><a href="{% url 'blog:post' post.author post.id %}">{{ post.title }}</a>
                    ({{ post.date_created }})</h4></td>
            </tr>
            <tr>
                <td>
                    <p>{{ post.get_preview }}</p>
                </td>
                {% if request.user == myuser %}
                <td><a href={% url 'blog:delete_post' post.id %}>Удалить</a></td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
    {% paginate %}
    {% endif %}
{% endblock content %}